### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by KamilSJaron** [RossLab/genomic-evidence-of-PGE-in-globular-springtails#1]
bookmarks of things not to forget to fix:

- [x] submit the second fastq files for WW5-4 and WW5-6 samples and add their assigned IDs to the table of samples.
- [x] merge the two mapping scripts to `scripts/map_reads_to_Afus1.sh` script (while pulling info from the sample table)
- [x] rename linked files in the repo so I don't have to recompute everything
